language: node_js

node_js:
  - "9.5.0"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm install -g gatsby'

script:
  - 'npm run build'

after_success:
  - 'npm run deploy'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master